[ids]
*

[main]
# Physical Caps Lock acts as Escape on tap, Control on hold
capslock = overload(control, esc)

# Physical Alt key functions as Super
leftalt = leftmeta

# Physical Ctrl key functions as Alt
leftcontrol = leftalt

# Physical Windows key functions as Caps Lock
leftmeta = capslock
